puts "BSG-info: Running script [info script]\n"

create_die_area -coordinate { 0 0 2895 2895 } 

set_port_side -side right p_ci_0_i
set_port_side -side right p_ci_1_i
set_port_side -side right p_ci_2_i
set_port_side -side right p_ci_3_i
set_port_side -side right p_ci_4_i
set_port_side -side right p_ci_clk_i
set_port_side -side right p_ci_tkn_o
set_port_side -side right p_ci_v_i
set_port_side -side right p_ci_5_i
set_port_side -side right p_ci_6_i
set_port_side -side right p_ci_7_i
set_port_side -side right p_ci_8_i
set_port_side -side right p_bsg_tag_en_i
set_port_side -side right p_bsg_tag_data_i
set_port_side -side right p_bsg_tag_clk_i
set_port_side -side right p_ddr_dm_3_o
set_port_side -side right p_ddr_dqs_p_3_io
set_port_side -side right p_ddr_dqs_n_3_io
set_port_side -side right p_ddr_dq_24_io
set_port_side -side right p_ddr_dq_25_io
set_port_side -side right p_ddr_dq_26_io
set_port_side -side right p_ddr_dq_27_io
set_port_side -side right p_ddr_dq_28_io
set_port_side -side right p_ddr_dq_29_io
set_port_side -side right p_ddr_dq_30_io
set_port_side -side right p_ddr_dq_31_io
set_port_side -side right p_ddr_dq_16_io
set_port_side -side right p_ddr_dq_17_io
set_port_side -side right p_ddr_dq_18_io
set_port_side -side right p_ddr_dq_19_io
set_port_side -side right p_ddr_dq_20_io
set_port_side -side right p_ddr_dq_21_io
set_port_side -side right p_ddr_dq_22_io
set_port_side -side right p_ddr_dq_23_io

set_port_side -side bottom p_ddr_dm_2_o
set_port_side -side bottom p_ddr_dqs_p_2_io
set_port_side -side bottom p_ddr_dqs_n_2_io
set_port_side -side bottom p_ddr_ck_p_o
set_port_side -side bottom p_ddr_ck_n_o
set_port_side -side bottom p_ddr_cke_o
set_port_side -side bottom p_ddr_cs_n_o
set_port_side -side bottom p_ddr_ras_n_o
set_port_side -side bottom p_ddr_cas_n_o
set_port_side -side bottom p_ddr_we_n_o
set_port_side -side bottom p_ddr_reset_n_o
set_port_side -side bottom p_ddr_odt_o
set_port_side -side bottom p_ddr_addr_0_o
set_port_side -side bottom p_ddr_addr_1_o
set_port_side -side bottom p_ddr_addr_2_o
set_port_side -side bottom p_ddr_addr_3_o
set_port_side -side bottom p_ddr_addr_4_o
set_port_side -side bottom p_ddr_addr_5_o
set_port_side -side bottom p_ddr_addr_6_o
set_port_side -side bottom p_ddr_addr_7_o
set_port_side -side bottom p_ddr_addr_8_o
set_port_side -side bottom p_ddr_addr_9_o
set_port_side -side bottom p_ddr_addr_10_o
set_port_side -side bottom p_ddr_addr_11_o
set_port_side -side bottom p_ddr_addr_12_o
set_port_side -side bottom p_ddr_addr_13_o
set_port_side -side bottom p_ddr_addr_14_o
set_port_side -side bottom p_ddr_addr_15_o
set_port_side -side bottom p_ddr_ba_0_o
set_port_side -side bottom p_ddr_ba_1_o
set_port_side -side bottom p_ddr_ba_2_o
set_port_side -side bottom p_ddr_dqs_p_1_io
set_port_side -side bottom p_ddr_dqs_n_1_io
set_port_side -side bottom p_ddr_dm_1_o

set_port_side -side left p_ddr_dq_8_io
set_port_side -side left p_ddr_dq_9_io
set_port_side -side left p_ddr_dq_10_io
set_port_side -side left p_ddr_dq_11_io
set_port_side -side left p_ddr_dq_12_io
set_port_side -side left p_ddr_dq_13_io
set_port_side -side left p_ddr_dq_14_io
set_port_side -side left p_ddr_dq_15_io
set_port_side -side left p_ddr_dqs_p_0_io
set_port_side -side left p_ddr_dqs_n_0_io
set_port_side -side left p_ddr_dm_0_o
set_port_side -side left p_ddr_dq_0_io
set_port_side -side left p_ddr_dq_1_io
set_port_side -side left p_ddr_dq_2_io
set_port_side -side left p_ddr_dq_3_io
set_port_side -side left p_ddr_dq_4_io
set_port_side -side left p_ddr_dq_5_io
set_port_side -side left p_ddr_dq_6_io
set_port_side -side left p_ddr_dq_7_io
set_port_side -side left p_bsg_tag_data_o
set_port_side -side left p_bsg_tag_clk_o
set_port_side -side left p_co2_0_o
set_port_side -side left p_co2_1_o
set_port_side -side left p_co2_2_o
set_port_side -side left p_co2_3_o
set_port_side -side left p_co2_4_o
set_port_side -side left p_co2_clk_o
set_port_side -side left p_co2_tkn_i
set_port_side -side left p_co2_v_o
set_port_side -side left p_co2_5_o
set_port_side -side left p_co2_6_o
set_port_side -side left p_co2_7_o
set_port_side -side left p_co2_8_o

set_port_side -side top p_co_0_i
set_port_side -side top p_co_1_i
set_port_side -side top p_co_2_i
set_port_side -side top p_co_3_i
set_port_side -side top p_co_4_i
set_port_side -side top p_co_clk_i
set_port_side -side top p_co_tkn_o
set_port_side -side top p_co_v_i
set_port_side -side top p_co_5_i
set_port_side -side top p_co_6_i
set_port_side -side top p_co_7_i
set_port_side -side top p_co_8_i
set_port_side -side top p_clk_A_i
set_port_side -side top p_clk_B_i
set_port_side -side top p_clk_C_i
set_port_side -side top p_clk_o
set_port_side -side top p_clk_async_reset_i
set_port_side -side top p_misc_o
set_port_side -side top p_sel_0_i
set_port_side -side top p_sel_1_i
set_port_side -side top p_sel_2_i
set_port_side -side top p_core_async_reset_i
set_port_side -side top p_ci2_0_o
set_port_side -side top p_ci2_1_o
set_port_side -side top p_ci2_2_o
set_port_side -side top p_ci2_3_o
set_port_side -side top p_ci2_4_o
set_port_side -side top p_ci2_clk_o
set_port_side -side top p_ci2_tkn_i
set_port_side -side top p_ci2_v_o
set_port_side -side top p_ci2_5_o
set_port_side -side top p_ci2_6_o
set_port_side -side top p_ci2_7_o
set_port_side -side top p_ci2_8_o

puts "BSG-info: Completed script [info script]\n"
