set_pad_physical_constraints -side 1 -pad_name corner_ul
set_pad_physical_constraints -side 2 -pad_name corner_ur
set_pad_physical_constraints -side 3 -pad_name corner_lr
set_pad_physical_constraints -side 4 -pad_name corner_ll

set_pad_physical_constraints -side 3 -order 68 -min_left_iospace 92.5 -min_right_iospace 10 -pad_name ci_0_i
set_pad_physical_constraints -side 3 -order 67 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_0
set_pad_physical_constraints -side 3 -order 66 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_1_i
set_pad_physical_constraints -side 3 -order 65 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_0
set_pad_physical_constraints -side 3 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_2_i
set_pad_physical_constraints -side 3 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_0
set_pad_physical_constraints -side 3 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_3_i
set_pad_physical_constraints -side 3 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_0
set_pad_physical_constraints -side 3 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_4_i
set_pad_physical_constraints -side 3 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_1
set_pad_physical_constraints -side 3 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_clk_i
set_pad_physical_constraints -side 3 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_1
set_pad_physical_constraints -side 3 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_tkn_o
set_pad_physical_constraints -side 3 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_1
set_pad_physical_constraints -side 3 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_v_i
set_pad_physical_constraints -side 3 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_1
set_pad_physical_constraints -side 3 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_5_i
set_pad_physical_constraints -side 3 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_2
set_pad_physical_constraints -side 3 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_6_i
set_pad_physical_constraints -side 3 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_2
set_pad_physical_constraints -side 3 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_7_i
set_pad_physical_constraints -side 3 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_2
set_pad_physical_constraints -side 3 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci_8_i
set_pad_physical_constraints -side 3 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_2
set_pad_physical_constraints -side 3 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name bsg_tag_en_i
set_pad_physical_constraints -side 3 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_3
set_pad_physical_constraints -side 3 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name bsg_tag_data_i
set_pad_physical_constraints -side 3 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_3
set_pad_physical_constraints -side 3 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name bsg_tag_clk_i
set_pad_physical_constraints -side 3 -order 39 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_3
set_pad_physical_constraints -side 3 -order 38 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dm_3_o
set_pad_physical_constraints -side 3 -order 37 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_3
set_pad_physical_constraints -side 3 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_p_3_io
set_pad_physical_constraints -side 3 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_4
set_pad_physical_constraints -side 3 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_n_3_io
set_pad_physical_constraints -side 3 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_4
set_pad_physical_constraints -side 3 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_24_io
set_pad_physical_constraints -side 3 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_4
set_pad_physical_constraints -side 3 -order 30 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_25_io
set_pad_physical_constraints -side 3 -order 29 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_4
set_pad_physical_constraints -side 3 -order 28 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_26_io
set_pad_physical_constraints -side 3 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_5
set_pad_physical_constraints -side 3 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_27_io
set_pad_physical_constraints -side 3 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_5
set_pad_physical_constraints -side 3 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_28_io
set_pad_physical_constraints -side 3 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_5
set_pad_physical_constraints -side 3 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_29_io
set_pad_physical_constraints -side 3 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_5
set_pad_physical_constraints -side 3 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_30_io
set_pad_physical_constraints -side 3 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_6
set_pad_physical_constraints -side 3 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_31_io
set_pad_physical_constraints -side 3 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_6
set_pad_physical_constraints -side 3 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_16_io
set_pad_physical_constraints -side 3 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_6
set_pad_physical_constraints -side 3 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_17_io
set_pad_physical_constraints -side 3 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_6
set_pad_physical_constraints -side 3 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_18_io
set_pad_physical_constraints -side 3 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_7
set_pad_physical_constraints -side 3 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_19_io
set_pad_physical_constraints -side 3 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_r_7
set_pad_physical_constraints -side 3 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_20_io
set_pad_physical_constraints -side 3 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_r_7
set_pad_physical_constraints -side 3 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_21_io
set_pad_physical_constraints -side 3 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_r_7
set_pad_physical_constraints -side 3 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_22_io
set_pad_physical_constraints -side 3 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_r_8
set_pad_physical_constraints -side 3 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_23_io
set_pad_physical_constraints -side 3 -order 1  -min_left_iospace 10 -min_right_iospace 92.5 -pad_name vss_r_8



set_pad_physical_constraints -side 4 -order 68 -min_left_iospace 92.5 -min_right_iospace 10 -pad_name ddr_dm_2_o
set_pad_physical_constraints -side 4 -order 67 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_0
set_pad_physical_constraints -side 4 -order 66 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_p_2_io
set_pad_physical_constraints -side 4 -order 65 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_0
set_pad_physical_constraints -side 4 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_n_2_io
set_pad_physical_constraints -side 4 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_0
set_pad_physical_constraints -side 4 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_ck_p_o
set_pad_physical_constraints -side 4 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_0
set_pad_physical_constraints -side 4 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_ck_n_o
set_pad_physical_constraints -side 4 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_1
set_pad_physical_constraints -side 4 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_cke_o
set_pad_physical_constraints -side 4 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_1
set_pad_physical_constraints -side 4 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_cs_n_o
set_pad_physical_constraints -side 4 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_1
set_pad_physical_constraints -side 4 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_ras_n_o
set_pad_physical_constraints -side 4 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_1
set_pad_physical_constraints -side 4 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_cas_n_o
set_pad_physical_constraints -side 4 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_2
set_pad_physical_constraints -side 4 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_we_n_o
set_pad_physical_constraints -side 4 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_2
set_pad_physical_constraints -side 4 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_reset_n_o
set_pad_physical_constraints -side 4 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_2
set_pad_physical_constraints -side 4 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_odt_o
set_pad_physical_constraints -side 4 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_2
set_pad_physical_constraints -side 4 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_0_o
set_pad_physical_constraints -side 4 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_3
set_pad_physical_constraints -side 4 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_1_o
set_pad_physical_constraints -side 4 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_3
set_pad_physical_constraints -side 4 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_2_o
set_pad_physical_constraints -side 4 -order 39 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_3
set_pad_physical_constraints -side 4 -order 38 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_3_o
set_pad_physical_constraints -side 4 -order 37 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_3
set_pad_physical_constraints -side 4 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_4_o
set_pad_physical_constraints -side 4 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_4
set_pad_physical_constraints -side 4 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_5_o
set_pad_physical_constraints -side 4 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_4
set_pad_physical_constraints -side 4 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_6_o
set_pad_physical_constraints -side 4 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_4
set_pad_physical_constraints -side 4 -order 30 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_7_o
set_pad_physical_constraints -side 4 -order 29 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_4
set_pad_physical_constraints -side 4 -order 28 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_8_o
set_pad_physical_constraints -side 4 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_5
set_pad_physical_constraints -side 4 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_9_o
set_pad_physical_constraints -side 4 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_5
set_pad_physical_constraints -side 4 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_10_o
set_pad_physical_constraints -side 4 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_5
set_pad_physical_constraints -side 4 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_11_o
set_pad_physical_constraints -side 4 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_5
set_pad_physical_constraints -side 4 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_12_o
set_pad_physical_constraints -side 4 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_6
set_pad_physical_constraints -side 4 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_13_o
set_pad_physical_constraints -side 4 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_6
set_pad_physical_constraints -side 4 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_14_o
set_pad_physical_constraints -side 4 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_6
set_pad_physical_constraints -side 4 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_addr_15_o
set_pad_physical_constraints -side 4 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_6
set_pad_physical_constraints -side 4 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_ba_0_o
set_pad_physical_constraints -side 4 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_7
set_pad_physical_constraints -side 4 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_ba_1_o
set_pad_physical_constraints -side 4 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_b_7
set_pad_physical_constraints -side 4 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_ba_2_o
set_pad_physical_constraints -side 4 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_b_7
set_pad_physical_constraints -side 4 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_p_1_io
set_pad_physical_constraints -side 4 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_b_7
set_pad_physical_constraints -side 4 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_n_1_io
set_pad_physical_constraints -side 4 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_b_8
set_pad_physical_constraints -side 4 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dm_1_o
set_pad_physical_constraints -side 4 -order 1  -min_left_iospace 10 -min_right_iospace 92.5 -pad_name vzz_b_8



set_pad_physical_constraints -side 1 -order 1  -min_left_iospace 10 -min_right_iospace 152.5 -pad_name ddr_dq_8_io
set_pad_physical_constraints -side 1 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_0
set_pad_physical_constraints -side 1 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_9_io
set_pad_physical_constraints -side 1 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_0
set_pad_physical_constraints -side 1 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_10_io
set_pad_physical_constraints -side 1 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_0
set_pad_physical_constraints -side 1 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_11_io
set_pad_physical_constraints -side 1 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_0
set_pad_physical_constraints -side 1 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_12_io
set_pad_physical_constraints -side 1 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_1
set_pad_physical_constraints -side 1 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_13_io
set_pad_physical_constraints -side 1 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_1
set_pad_physical_constraints -side 1 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_14_io
set_pad_physical_constraints -side 1 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_1
set_pad_physical_constraints -side 1 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_15_io
set_pad_physical_constraints -side 1 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_1
set_pad_physical_constraints -side 1 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_p_0_io
set_pad_physical_constraints -side 1 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_2
set_pad_physical_constraints -side 1 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dqs_n_0_io
set_pad_physical_constraints -side 1 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_2
set_pad_physical_constraints -side 1 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dm_0_o
set_pad_physical_constraints -side 1 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_2
set_pad_physical_constraints -side 1 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_0_io
set_pad_physical_constraints -side 1 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_2
set_pad_physical_constraints -side 1 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_1_io
set_pad_physical_constraints -side 1 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_3
set_pad_physical_constraints -side 1 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_2_io
set_pad_physical_constraints -side 1 -order 28 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_3
set_pad_physical_constraints -side 1 -order 29 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_3_io
set_pad_physical_constraints -side 1 -order 30 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_3
set_pad_physical_constraints -side 1 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_4_io
set_pad_physical_constraints -side 1 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_3
set_pad_physical_constraints -side 1 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_5_io
set_pad_physical_constraints -side 1 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_4
set_pad_physical_constraints -side 1 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_6_io
set_pad_physical_constraints -side 1 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_4
set_pad_physical_constraints -side 1 -order 37 -min_left_iospace 10 -min_right_iospace 10 -pad_name ddr_dq_7_io
set_pad_physical_constraints -side 1 -order 38 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_4
set_pad_physical_constraints -side 1 -order 39 -min_left_iospace 10 -min_right_iospace 10 -pad_name bsg_tag_data_o
set_pad_physical_constraints -side 1 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_4
set_pad_physical_constraints -side 1 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name bsg_tag_clk_o
set_pad_physical_constraints -side 1 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_5
set_pad_physical_constraints -side 1 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_0_o
set_pad_physical_constraints -side 1 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_5
set_pad_physical_constraints -side 1 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_1_o
set_pad_physical_constraints -side 1 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_5
set_pad_physical_constraints -side 1 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_2_o
set_pad_physical_constraints -side 1 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_5
set_pad_physical_constraints -side 1 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_3_o
set_pad_physical_constraints -side 1 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_6
set_pad_physical_constraints -side 1 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_4_o
set_pad_physical_constraints -side 1 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_6
set_pad_physical_constraints -side 1 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_clk_o
set_pad_physical_constraints -side 1 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_6
set_pad_physical_constraints -side 1 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_tkn_i
set_pad_physical_constraints -side 1 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_6
set_pad_physical_constraints -side 1 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_v_o
set_pad_physical_constraints -side 1 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_l_7
set_pad_physical_constraints -side 1 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_5_o
set_pad_physical_constraints -side 1 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_l_7
set_pad_physical_constraints -side 1 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_6_o
set_pad_physical_constraints -side 1 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_l_7
set_pad_physical_constraints -side 1 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name co2_7_o
set_pad_physical_constraints -side 1 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_l_7
set_pad_physical_constraints -side 1 -order 65 -min_left_iospace 152.5 -min_right_iospace 10 -pad_name co2_8_o



set_pad_physical_constraints -side 2 -order 1  -min_left_iospace 10 -min_right_iospace 72.5 -pad_name vdd_t_0
set_pad_physical_constraints -side 2 -order 2  -min_left_iospace 10 -min_right_iospace 10 -pad_name co_0_i
set_pad_physical_constraints -side 2 -order 3  -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_0
set_pad_physical_constraints -side 2 -order 4  -min_left_iospace 10 -min_right_iospace 10 -pad_name co_1_i
set_pad_physical_constraints -side 2 -order 5  -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_t_0
set_pad_physical_constraints -side 2 -order 6  -min_left_iospace 10 -min_right_iospace 10 -pad_name co_2_i
set_pad_physical_constraints -side 2 -order 7  -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_0
set_pad_physical_constraints -side 2 -order 8  -min_left_iospace 10 -min_right_iospace 10 -pad_name co_3_i
set_pad_physical_constraints -side 2 -order 9  -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_t_1
set_pad_physical_constraints -side 2 -order 10 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_4_i
set_pad_physical_constraints -side 2 -order 11 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_1
set_pad_physical_constraints -side 2 -order 12 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_clk_i
set_pad_physical_constraints -side 2 -order 13 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_t_1
set_pad_physical_constraints -side 2 -order 14 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_tkn_o
set_pad_physical_constraints -side 2 -order 15 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_1
set_pad_physical_constraints -side 2 -order 16 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_v_i
set_pad_physical_constraints -side 2 -order 17 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_t_2
set_pad_physical_constraints -side 2 -order 18 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_5_i
set_pad_physical_constraints -side 2 -order 19 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_2
set_pad_physical_constraints -side 2 -order 20 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_6_i
set_pad_physical_constraints -side 2 -order 21 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_t_2
set_pad_physical_constraints -side 2 -order 22 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_7_i
set_pad_physical_constraints -side 2 -order 23 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_2
set_pad_physical_constraints -side 2 -order 24 -min_left_iospace 10 -min_right_iospace 10 -pad_name co_8_i
set_pad_physical_constraints -side 2 -order 25 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_t_3
set_pad_physical_constraints -side 2 -order 26 -min_left_iospace 10 -min_right_iospace 10 -pad_name clk_A_i
set_pad_physical_constraints -side 2 -order 27 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_3
set_pad_physical_constraints -side 2 -order 28 -min_left_iospace  0 -min_right_iospace 10 -pad_name clk_B_i
set_pad_physical_constraints -side 2 -order 29 -min_left_iospace  0 -min_right_iospace  0 -pad_name breaker_t_0
set_pad_physical_constraints -side 2 -order 30 -min_left_iospace 10 -min_right_iospace  0 -pad_name v18_t_pll
set_pad_physical_constraints -side 2 -order 31 -min_left_iospace 10 -min_right_iospace 10 -pad_name clk_C_i
set_pad_physical_constraints -side 2 -order 32 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_pll
set_pad_physical_constraints -side 2 -order 33 -min_left_iospace 10 -min_right_iospace 10 -pad_name clk_o
set_pad_physical_constraints -side 2 -order 34 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_t_pll
set_pad_physical_constraints -side 2 -order 35 -min_left_iospace 10 -min_right_iospace 10 -pad_name clk_async_reset_i
set_pad_physical_constraints -side 2 -order 36 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_pll
set_pad_physical_constraints -side 2 -order 37 -min_left_iospace  0 -min_right_iospace 10 -pad_name misc_o
set_pad_physical_constraints -side 2 -order 38 -min_left_iospace  0 -min_right_iospace  0 -pad_name breaker_t_1
set_pad_physical_constraints -side 2 -order 39 -min_left_iospace 10 -min_right_iospace  0 -pad_name vdd_t_4
set_pad_physical_constraints -side 2 -order 40 -min_left_iospace 10 -min_right_iospace 10 -pad_name sel_0_i
set_pad_physical_constraints -side 2 -order 41 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_4
set_pad_physical_constraints -side 2 -order 42 -min_left_iospace 10 -min_right_iospace 10 -pad_name sel_1_i
set_pad_physical_constraints -side 2 -order 43 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_t_4
set_pad_physical_constraints -side 2 -order 44 -min_left_iospace 10 -min_right_iospace 10 -pad_name sel_2_i
set_pad_physical_constraints -side 2 -order 45 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_4
set_pad_physical_constraints -side 2 -order 46 -min_left_iospace 10 -min_right_iospace 10 -pad_name core_async_reset_i
set_pad_physical_constraints -side 2 -order 47 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_t_5
set_pad_physical_constraints -side 2 -order 48 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_0_o
set_pad_physical_constraints -side 2 -order 49 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_5
set_pad_physical_constraints -side 2 -order 50 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_1_o
set_pad_physical_constraints -side 2 -order 51 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_t_5
set_pad_physical_constraints -side 2 -order 52 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_2_o
set_pad_physical_constraints -side 2 -order 53 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_5
set_pad_physical_constraints -side 2 -order 54 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_3_o
set_pad_physical_constraints -side 2 -order 55 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_t_6
set_pad_physical_constraints -side 2 -order 56 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_4_o
set_pad_physical_constraints -side 2 -order 57 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_6
set_pad_physical_constraints -side 2 -order 58 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_clk_o
set_pad_physical_constraints -side 2 -order 59 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_t_6
set_pad_physical_constraints -side 2 -order 60 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_tkn_i
set_pad_physical_constraints -side 2 -order 61 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_6
set_pad_physical_constraints -side 2 -order 62 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_v_o
set_pad_physical_constraints -side 2 -order 63 -min_left_iospace 10 -min_right_iospace 10 -pad_name vdd_t_7
set_pad_physical_constraints -side 2 -order 64 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_5_o
set_pad_physical_constraints -side 2 -order 65 -min_left_iospace 10 -min_right_iospace 10 -pad_name vss_t_7
set_pad_physical_constraints -side 2 -order 66 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_6_o
set_pad_physical_constraints -side 2 -order 67 -min_left_iospace 10 -min_right_iospace 10 -pad_name v18_t_7
set_pad_physical_constraints -side 2 -order 68 -min_left_iospace 10 -min_right_iospace 10 -pad_name ci2_7_o
set_pad_physical_constraints -side 2 -order 69 -min_left_iospace 10 -min_right_iospace 10 -pad_name vzz_t_7
set_pad_physical_constraints -side 2 -order 70 -min_left_iospace 72.5 -min_right_iospace 10 -pad_name ci2_8_o
